"use client";
import { useActionState, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowUp, CalendarDays, ChevronDown, ChevronLeft, ChevronRight, CircleAlert, Clock3, CreditCard, ExternalLink, Info, Plus, Search, Wallet, X } from "lucide-react";
import { registrarPagamento } from "@/app/app/(sistema)/contratos/acoes";
import { cancelarDespesa, pagarDespesa, salvarDespesa } from "@/app/app/(sistema)/financeiro/acoes";
import { CATEGORIAS_DESPESA, despesasDoPeriodo, resumoFinanceiro, serieFinanceiro, situacaoRecebivel, somaValores, type DadosFinanceiro, type Despesa, type Recebivel } from "@/lib/financeiro";
import { InputMascara } from "@/components/InputMascara";
import { dataCurta, reais } from "@/lib/propostas";
import type { EstadoFormulario } from "@/lib/formulario";
import "./financeiro.css";

const ABAS = [{ id: "geral", nome: "Visão geral" }, { id: "receber", nome: "Contas a receber" }, { id: "despesas", nome: "Despesas" }, { id: "asaas", nome: "Asaas" }] as const;
const normalizar = (s: string) => s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
const nomeMes = (mes: string, curto = false) => new Intl.DateTimeFormat("pt-BR", { month: curto ? "short" : "long", ...(curto ? {} : { year: "numeric" }), timeZone: "UTC" }).format(new Date(`${mes}-01T12:00:00Z`)).replace(/^./, c => c.toUpperCase()).replace(".", "");
type Modal = { tipo: "nova"; id: string } | { tipo: "receber"; pagamento: Recebivel } | { tipo: "pagar" | "cancelar"; despesa: Despesa } | null;
export function Financeiro({ dados, abaInicial, caminho = "/app/financeiro" }: { dados: DadosFinanceiro; abaInicial?: string; caminho?: string }) {
  const router = useRouter(), [aba, setAba] = useState(ABAS.some(a => a.id === abaInicial) ? abaInicial! : "geral");
  const [busca, setBusca] = useState(""), [situacao, setSituacao] = useState("todos"), [pagina, setPagina] = useState(1), [modal, setModal] = useState<Modal>(null);
  useEffect(() => { setAba(ABAS.some(a => a.id === abaInicial) ? abaInicial! : "geral"); }, [abaInicial]);
  useEffect(() => { setPagina(1); }, [busca, situacao, aba, dados.mes]);
  const resumo = useMemo(() => resumoFinanceiro(dados.recebiveis, dados.despesas, dados.mes, dados.hoje), [dados]);
  const editar = dados.podeEditar && !dados.somenteLeitura;
  const recebiveis = dados.recebiveis.filter(p => (aba === "geral" ? !p.pagoEm : !p.pagoEm || p.pagoEm.startsWith(dados.mes)) && normalizar(`${p.cliente} ${p.projeto}`).includes(normalizar(busca)) && (situacao === "todos" || situacaoRecebivel(p, dados.hoje) === situacao))
    .sort((a, b) => Number(!!a.pagoEm) - Number(!!b.pagoEm) || (a.vencimento ?? "9999").localeCompare(b.vencimento ?? "9999") || a.cliente.localeCompare(b.cliente));
  const despesas = despesasDoPeriodo(dados.despesas, dados.mes).filter(d => normalizar(`${d.descricao} ${d.fornecedor ?? ""}`).includes(normalizar(busca)) && (situacao === "todos" || situacao === (d.pago_em ? "pago" : d.vencimento < dados.hoje ? "atraso" : "pendente")))
    .sort((a,b)=>a.vencimento.localeCompare(b.vencimento));
  const tamanho = aba === "geral" ? 4 : 15, lista = aba === "despesas" ? despesas : recebiveis;
  const totalPaginas = Math.max(1, Math.ceil(lista.length / tamanho)), paginaAtual = Math.min(pagina, totalPaginas);
  const recibos = recebiveis.slice((paginaAtual - 1) * tamanho, paginaAtual * tamanho), gastos = despesas.slice((paginaAtual - 1) * tamanho, paginaAtual * tamanho);
  const trocarAba = (id: string) => { setAba(id); setBusca(""); setSituacao("todos"); router.replace(`${caminho}?mes=${dados.mes}&aba=${id}`, { scroll: false }); };
  const fechar = () => { setModal(null); router.refresh(); };
  return <div className="financeiro">
    <header className="fin-cabecalho"><div><h1>Financeiro</h1><p>Acompanhe os recebimentos e as despesas do escritório.</p></div><div className="fin-acoes">
      <label className="fin-periodo"><CalendarDays size={19} aria-hidden="true"/><span>{nomeMes(dados.mes)}</span><ChevronDown size={16} aria-hidden="true"/><input aria-label="Mês do financeiro" type="month" min="2000-01" max="2100-12" value={dados.mes} onChange={e => { if (e.target.value) router.push(`${caminho}?mes=${e.target.value}&aba=${aba}`, {scroll:false}); }}/></label>
      {editar && <button className="botao botao-primario fin-nova" onClick={() => setModal({tipo:"nova",id:crypto.randomUUID()})}><Plus size={20} aria-hidden="true"/>Nova despesa</button>}
    </div></header>
    <nav className="fin-abas" aria-label="Seções do financeiro">{ABAS.map(a=><button key={a.id} className={aba===a.id?"ativo":""} aria-current={aba===a.id?"page":undefined} onClick={()=>trocarAba(a.id)}>{a.nome}</button>)}</nav>
    {dados.somenteLeitura && <p className="fin-aviso" role="status">Seu escritório está em modo leitura. Você pode consultar os registros.</p>}
    {aba==="geral" && <>
      <div className="fin-resumos">
        <Resumo titulo="Recebido no mês" valor={resumo.recebido} detalhe="Pagamentos confirmados" cor="verde" icone={<ArrowUp size={25}/>}/>
        <Resumo titulo="A receber" valor={resumo.aReceber} detalhe="Parcelas ainda não pagas" cor="azul" icone={<Clock3 size={24}/>}/>
        <Resumo titulo="Em atraso" valor={resumo.emAtraso} detalhe={`${resumo.parcelasAtrasadas} ${resumo.parcelasAtrasadas===1?"parcela vencida":"parcelas vencidas"}`} cor="vermelho" icone={<CircleAlert size={24}/>}/>
        <Resumo titulo="Despesas do mês" valor={resumo.despesas} detalhe="Despesas pagas" cor="preto" icone={<CreditCard size={24}/>}/>
      </div>
      <div className="fin-paineis"><Grafico dados={dados}/><PainelAsaas saldo={dados.asaas}/></div>
    </>}
    {aba==="asaas" && <div className="fin-asaas-pagina"><PainelAsaas saldo={dados.asaas}/><section className="fin-cartao fin-explicacao"><h2>Pagamento e saldo são etapas diferentes</h2><p>O Asaas confirma o pagamento e o NorteArq gera a baixa e o recibo automaticamente.</p><p>No cartão, uma compra aprovada quita a obrigação do cliente. As parcelas ficam disponíveis ao escritório nos prazos do Asaas.</p><p>O saldo e os valores a liberar representam a conta Asaas inteira. As taxas consideram as cobranças pagas no mês selecionado.</p><p className="fin-nota">As consultas podem levar até 5 minutos para atualizar. A consulta nesta tela não faz saques, transferências ou pagamentos.</p><Link className="fin-link" href="/app/configuracoes#cobranca">Gerenciar a conexão com o Asaas</Link></section></div>}
    {aba!=="asaas" && <section className="fin-cartao fin-listagem" aria-label={aba==="despesas"?"Despesas":"Contas a receber"}>
      <div className="fin-lista-cabecalho"><h2>{aba==="despesas"?"Despesas":"Contas a receber"}</h2><div className="fin-filtros"><label className="fin-busca"><Search size={18} aria-hidden="true"/><input aria-label={aba==="despesas"?"Buscar despesa ou fornecedor":"Buscar cliente ou projeto"} placeholder={aba==="despesas"?"Buscar despesa ou fornecedor":"Buscar cliente ou projeto"} value={busca} onChange={e=>setBusca(e.target.value)}/></label><select aria-label="Filtrar situação" value={situacao} onChange={e=>setSituacao(e.target.value)}><option value="todos">Todas as situações</option><option value="pendente">Pendente</option><option value="atraso">Em atraso</option>{aba!=="geral"&&<option value="pago">Pago</option>}</select>{aba==="geral"&&<button className="fin-link" onClick={()=>trocarAba("receber")}>Ver todas</button>}</div></div>
      {aba==="despesas" && <p className="fin-contexto">{nomeMes(dados.mes)} · {despesas.length} {despesas.length===1?"despesa":"despesas"} · Total listado: {reais(somaValores(despesas.map(d=>d.valor)))}</p>}
      <div className="fin-tabela-rolagem"><table className="fin-tabela"><thead><tr>{aba==="despesas"?<><th>Despesa / fornecedor</th><th>Categoria</th></>:<><th>Cliente / projeto</th><th>Parcela</th></>}<th>Vencimento</th><th>Valor</th><th>Situação</th>{aba!=="despesas"&&<th>Pagamento</th>}<th>Ação</th></tr></thead><tbody>
        {aba==="despesas" ? gastos.map(d=><tr key={d.id}><td><strong>{d.descricao}</strong><small>{d.fornecedor || "Sem fornecedor informado"}</small></td><td>{CATEGORIAS_DESPESA[d.categoria]}</td><td>{dataCurta(d.vencimento)}</td><td className="fin-valor">{reais(d.valor)}</td><td><Selo situacao={d.pago_em?"pago":d.vencimento<dados.hoje?"atraso":"pendente"}/>{d.pago_em&&<small>Pago em {dataCurta(d.pago_em)}</small>}</td><td><div className="fin-linha-acoes">{editar&&!d.pago_em&&<button className="fin-link" onClick={()=>setModal({tipo:"pagar",despesa:d})}>Registrar pagamento</button>}{editar&&<button className="fin-link fin-cancelar-link" onClick={()=>setModal({tipo:"cancelar",despesa:d})}>Cancelar despesa</button>}{!editar&&"—"}</div></td></tr>) : recibos.map(p=><tr key={p.id}><td><strong>{p.cliente}</strong><small>{p.projeto}</small></td><td>{p.descricao}</td><td>{p.vencimento?dataCurta(p.vencimento):<span className="fin-sem-data">Sem data definida</span>}</td><td className="fin-valor">{reais(p.valor)}</td><td><Selo situacao={situacaoRecebivel(p,dados.hoje)}/>{p.pagoEm&&<small>{p.checkout?"Compra aprovada":"Pago"} em {dataCurta(p.pagoEm)}</small>}</td><td>{forma(p)}{p.asaas&&<small>Asaas</small>}</td><td>{!p.pagoEm&&!p.asaas&&editar?<button className="fin-link" onClick={()=>setModal({tipo:"receber",pagamento:p})}>Registrar pagamento</button>:<Link className="fin-link" href={`/app/contratos/${p.contratoId}`}>Ver contrato</Link>}</td></tr>)}
        {!lista.length&&<tr><td colSpan={aba==="despesas"?6:7}><div className="fin-vazio"><Wallet size={28} aria-hidden="true"/><strong>{busca||situacao!=="todos"?"Nenhum registro encontrado":aba==="despesas"?"Nenhuma despesa neste período":aba==="geral"?"Nenhum pagamento pendente":"Nenhum recebimento neste período"}</strong><p>{busca||situacao!=="todos"?"Ajuste a busca ou a situação para ver outros registros.":aba==="despesas"?"Use Nova despesa para registrar os custos do escritório.":"Os pagamentos dos contratos assinados aparecem aqui automaticamente."}</p></div></td></tr>}
      </tbody></table></div>
      <div className="fin-lista-rodape"><p><Info size={16} aria-hidden="true"/>{aba==="despesas"?"Despesas canceladas saem dos totais e permanecem no histórico.":"Pagamentos no Asaas são atualizados automaticamente. Pix direto exige registro manual."}</p>{totalPaginas>1&&<div className="fin-paginacao"><button aria-label="Página anterior" disabled={paginaAtual===1} onClick={()=>setPagina(paginaAtual-1)}><ChevronLeft size={18}/></button><span>{paginaAtual} de {totalPaginas}</span><button aria-label="Próxima página" disabled={paginaAtual===totalPaginas} onClick={()=>setPagina(paginaAtual+1)}><ChevronRight size={18}/></button></div>}</div>
      {(aba==="receber"||aba==="despesas")&&<p className="fin-contexto">Pendências de todos os vencimentos e {aba==="despesas"?"despesas pagas":"pagamentos confirmados"} em {nomeMes(dados.mes).toLowerCase()}.</p>}
    </section>}
    {modal&&<Dialogo titulo={modal.tipo==="nova"?"Nova despesa":modal.tipo==="receber"?"Registrar recebimento":modal.tipo==="pagar"?"Registrar pagamento da despesa":"Cancelar despesa"} fechar={()=>setModal(null)}>
      {modal.tipo==="nova"?<FormDespesa id={modal.id} hoje={dados.hoje} fechar={fechar}/>:modal.tipo==="receber"?<FormRecebimento p={modal.pagamento} hoje={dados.hoje} fechar={fechar}/>:<FormSituacao despesa={modal.despesa} tipo={modal.tipo} hoje={dados.hoje} fechar={fechar}/>}
    </Dialogo>}
  </div>;
}
function forma(p: Recebivel) { const f=({transferencia:"Transferência",dinheiro:"Dinheiro",outro:"Outro",PIX:"Pix",pix:"Pix",BOLETO:"Boleto",boleto:"Boleto",CREDIT_CARD:"Cartão",cartao:"Cartão",UNDEFINED:"A escolher"} as Record<string,string>)[p.forma??""]??"Não definida"; return !p.asaas&&p.forma==="pix"?"Pix direto":f; }
function Resumo({ titulo, valor, detalhe, cor, icone }: {titulo:string;valor:number;detalhe:string;cor:string;icone:React.ReactNode}) { return <section className={`fin-cartao fin-resumo fin-${cor}`}><span className="fin-resumo-icone" aria-hidden="true">{icone}</span><div><h2>{titulo}</h2><strong>{reais(valor)}</strong><p>{detalhe}</p></div></section>; }
function Selo({situacao}:{situacao:string}) {return <span className={`fin-selo fin-selo-${situacao}`}><span aria-hidden="true"/>{situacao==="pago"?"Pago":situacao==="atraso"?"Em atraso":"Pendente"}</span>;}
function Grafico({dados}:{dados:DadosFinanceiro}) {
  const serie=serieFinanceiro(dados.recebiveis,dados.despesas,dados.mes), maior=Math.max(0,...serie.flatMap(s=>[s.entradas,s.saidas]));
  const magnitude=maior?10**Math.floor(Math.log10(maior)):1000, passo=maior?Math.ceil(maior/magnitude/4)*magnitude:1000, teto=passo*4;
  return <section className="fin-cartao fin-grafico"><div className="fin-painel-titulo"><h2>Entradas e saídas</h2><div className="fin-legenda"><span><i/>Entradas</span><span><i/>Saídas</span></div></div><div className="fin-plot" role="img" aria-label={serie.map(s=>`${nomeMes(s.mes)}: entradas ${reais(s.entradas)}, saídas ${reais(s.saidas)}`).join("; ")}>
    <div className="fin-eixo">{[4,3,2,1,0].map(i=><span key={i}>{new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(passo*i)}</span>)}</div>
    <div className="fin-barras-area"><div className="fin-grades">{[0,1,2,3,4].map(i=><span key={i}/>)}</div><div className="fin-barras">{serie.map(s=><div className="fin-coluna" key={s.mes}><div className="fin-par-barras"><div className="fin-barra fin-entrada" title={`Entradas: ${reais(s.entradas)}`} style={{height:`${s.entradas/teto*100}%`}}/><div className="fin-barra fin-saida" title={`Saídas: ${reais(s.saidas)}`} style={{height:`${s.saidas/teto*100}%`}}/></div><span>{nomeMes(s.mes,true)}/{s.mes.slice(2,4)}</span></div>)}</div></div>
  </div><p className="fin-nota">Entradas consideram pagamentos confirmados, incluindo compras aprovadas no cartão. Consulte o saldo disponível no Asaas.</p></section>;
}
function PainelAsaas({saldo}:{saldo:DadosFinanceiro["asaas"]}) {
  return <section className="fin-cartao fin-asaas"><div className="fin-painel-titulo"><h2><span className="fin-asaas-icone"><Wallet size={20} aria-hidden="true"/></span>Recebimentos no Asaas</h2><span className={`fin-conexao ${!saldo.ativo?"inativa":saldo.erro?"alerta":""}`}><i/>{!saldo.ativo?"Não conectado":saldo.teste?"Teste":saldo.erro?"Verificar":"Conectado"}</span></div>
    {saldo.ativo?<><dl><div><dt>Disponível para saque</dt><dd className="fin-saldo-disponivel">{reais(saldo.saldo)}</dd></div><div><dt>A liberar</dt><dd className="fin-saldo-futuro">{reais(saldo.aLiberar)}</dd></div><div><dt>Taxas do mês</dt><dd>{reais(saldo.taxas)}</dd></div></dl>{saldo.erro&&<p className="fin-aviso">Parte dos valores não pôde ser consultada. Confira no Asaas ou atualize em instantes.</p>}{saldo.teste&&<p className="fin-aviso">Ambiente de testes. Os valores não representam dinheiro real.</p>}<div className="fin-asaas-rodape"><p>Compra aprovada no cartão não significa saldo disponível.</p><a className="fin-link" href={saldo.teste?"https://sandbox.asaas.com":"https://www.asaas.com"} target="_blank" rel="noopener noreferrer">Ver detalhes no Asaas <ExternalLink size={13} aria-hidden="true"/></a></div></>:<div className="fin-asaas-desconectado"><p>Conecte sua conta para consultar o saldo e confirmar os pagamentos automaticamente.</p><Link className="botao botao-secundario" href="/app/configuracoes#cobranca">Conectar Asaas</Link><p className="fin-nota">Pix direto continua disponível, com registro manual dos recebimentos.</p></div>}
  </section>;
}
function Dialogo({titulo,fechar,children}:{titulo:string;fechar:()=>void;children:React.ReactNode}) {
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);
  return <dialog className="fin-dialogo" ref={ref} aria-labelledby="fin-dialogo-titulo" onCancel={fechar} onClick={e=>{if(e.target===ref.current){const r=ref.current.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)fechar();}}}><div className="fin-dialogo-cabecalho"><h2 id="fin-dialogo-titulo">{titulo}</h2><button className="fin-fechar" type="button" onClick={fechar} aria-label="Fechar"><X size={21}/></button></div>{children}</dialog>;
}
const inicial:EstadoFormulario={status:"inicial"};
function Mensagem({estado}:{estado:EstadoFormulario}) {return estado.status==="erro"?<p className="fin-aviso" role="alert">{estado.mensagem}</p>:null;}
function Campo({nome,rotulo,erro,children}:{nome:string;rotulo:string;erro?:string;children:React.ReactNode}) {return <div className="fin-campo"><label htmlFor={`fin-${nome}`}>{rotulo}</label>{children}{erro&&<small className="campo-erro" role="alert">{erro}</small>}</div>;}
function FormDespesa({id,hoje,fechar}:{id:string;hoje:string;fechar:()=>void}) {
  const [estado,action,pendente]=useActionState(salvarDespesa,inicial),[paga,setPaga]=useState(false);
  useEffect(()=>{if(estado.status==="sucesso")fechar();},[estado.status,fechar]);
  return <form action={action} className="fin-form"><input type="hidden" name="id" value={id}/><Mensagem estado={estado}/><Campo nome="descricao" rotulo="Descrição" erro={estado.erros?.descricao}><input id="fin-descricao" name="descricao" defaultValue={estado.valores?.descricao} required minLength={3} maxLength={160} placeholder="Ex.: Renderização do projeto"/></Campo><div className="fin-form-linha"><Campo nome="fornecedor" rotulo="Fornecedor (opcional)" erro={estado.erros?.fornecedor}><input id="fin-fornecedor" name="fornecedor" defaultValue={estado.valores?.fornecedor} maxLength={120}/></Campo><Campo nome="categoria" rotulo="Categoria" erro={estado.erros?.categoria}><select id="fin-categoria" name="categoria" defaultValue={estado.valores?.categoria ?? "fornecedor"}>{Object.entries(CATEGORIAS_DESPESA).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Campo></div><div className="fin-form-linha"><Campo nome="valor" rotulo="Valor (R$)" erro={estado.erros?.valor}><InputMascara mascara="dinheiro" id="fin-valor" name="valor" inputMode="decimal" required defaultValue={estado.valores?.valor} placeholder="0,00"/></Campo><Campo nome="vencimento" rotulo="Vencimento" erro={estado.erros?.vencimento}><input id="fin-vencimento" name="vencimento" type="date" required defaultValue={estado.valores?.vencimento ?? hoje}/></Campo></div><label className="fin-checkbox"><input type="checkbox" checked={paga} onChange={e=>setPaga(e.target.checked)}/>Esta despesa já foi paga</label>{paga?<Campo nome="pago_em" rotulo="Data do pagamento" erro={estado.erros?.pago_em}><input id="fin-pago_em" name="pago_em" type="date" required max={hoje} defaultValue={estado.valores?.pago_em ?? hoje}/></Campo>:<input type="hidden" name="pago_em" value=""/>}<Campo nome="observacao" rotulo="Observação (opcional)" erro={estado.erros?.observacao}><textarea id="fin-observacao" name="observacao" defaultValue={estado.valores?.observacao} maxLength={1000} rows={2}/></Campo><p className="fin-nota">Este registro organiza suas despesas. Não realiza pagamento bancário.</p><RodapeForm pendente={pendente} fechar={fechar} texto="Salvar despesa"/></form>;
}
function FormRecebimento({p,hoje,fechar}:{p:Recebivel;hoje:string;fechar:()=>void}) {
  const [estado,action,pendente]=useActionState(registrarPagamento,inicial);
  useEffect(()=>{if(estado.status==="sucesso")fechar();},[estado.status,fechar]);
  return <form action={action} className="fin-form"><input type="hidden" name="pagamento_id" value={p.id}/><p className="fin-form-resumo"><strong>{p.cliente}</strong><span>{p.descricao} · {reais(p.valor)}</span></p><Mensagem estado={estado}/><div className="fin-form-linha"><Campo nome="pago_em" rotulo="Data do pagamento" erro={estado.erros?.pago_em}><input id="fin-pago_em" name="pago_em" type="date" required max={hoje} defaultValue={estado.valores?.pago_em ?? hoje}/></Campo><Campo nome="forma" rotulo="Forma de pagamento" erro={estado.erros?.forma}><select id="fin-forma" name="forma" defaultValue="pix"><option value="pix">Pix</option><option value="transferencia">Transferência</option><option value="boleto">Boleto</option><option value="cartao">Cartão</option><option value="dinheiro">Dinheiro</option><option value="outro">Outro</option></select></Campo></div><Campo nome="observacao" rotulo="Observação ou comprovante (opcional)"><input id="fin-observacao" name="observacao" maxLength={300}/></Campo><p className="fin-nota">Confirme o recebimento na conta antes de registrar. O recibo será gerado; correções são feitas por estorno no contrato.</p><RodapeForm pendente={pendente} fechar={fechar} texto="Confirmar recebimento"/></form>;
}
function FormSituacao({despesa,tipo,hoje,fechar}:{despesa:Despesa;tipo:"pagar"|"cancelar";hoje:string;fechar:()=>void}) {
  const [estado,action,pendente]=useActionState(tipo==="pagar"?pagarDespesa:cancelarDespesa,inicial);
  useEffect(()=>{if(estado.status==="sucesso")fechar();},[estado.status,fechar]);
  return <form action={action} className="fin-form"><input type="hidden" name="id" value={despesa.id}/><p className="fin-form-resumo"><strong>{despesa.descricao}</strong><span>{reais(despesa.valor)}</span></p><Mensagem estado={estado}/>{tipo==="pagar"?<Campo nome="pago_em" rotulo="Data do pagamento" erro={estado.erros?.pago_em}><input id="fin-pago_em" name="pago_em" type="date" required defaultValue={hoje} max={hoje}/></Campo>:<><Campo nome="motivo" rotulo="Motivo do cancelamento" erro={estado.erros?.motivo}><textarea id="fin-motivo" name="motivo" required minLength={5} maxLength={300} rows={3}/></Campo><p className="fin-nota">A despesa sairá dos totais, mas seu histórico será preservado. Isso não desfaz um pagamento bancário.</p></>}<RodapeForm pendente={pendente} fechar={fechar} texto={tipo==="pagar"?"Confirmar registro":"Cancelar despesa"}/></form>;
}
function RodapeForm({pendente,fechar,texto}:{pendente:boolean;fechar:()=>void;texto:string}) {return <div className="fin-form-rodape"><button type="button" className="botao botao-fantasma" disabled={pendente} onClick={fechar}>Voltar</button><button type="submit" className="botao botao-primario" disabled={pendente}>{pendente?"Salvando…":texto}</button></div>;}
